import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Tech Blog",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-4/5 mx-auto">
          <header className="p-8 border-b rounded-bl-md rounded-br-md flex justify-between bg-blue-700">
            <Link href={"/"} className="text-white text-2xl font-semibold">
              The Tech Blog
            </Link>
            <Link
              href={"/publish"}
              className="bg-white rounded-md text-center p-1 text-blue-800 hover:bg-slate-300"
            >
              Publish new topic
            </Link>
          </header>
          <main className="p-4 text-lg">{children}</main>
        </div>
      </body>
    </html>
  );
}
